version: "3"
services:
  video-streaming:
    image: cosmtrek/air
    working_dir: /project-package/
    container_name: video-streaming
    ports:
      - "4000:80"
    volumes:
      - ./video-streaming/:/project-package/
    environment:
      - PORT=80

  history:
    image: cosmtrek/air
    working_dir: /project-package/
    container_name: history
    ports:
      - "4001:80"
    volumes:
      - ./history/:/project-package/
    environment:
      - PORT=80
    restart: "no"
  # history:
  #   image: history
  #   build:
  #     context: ./history
  #     dockerfile: Dockerfile
  #   container_name: history
  #   ports:
  #     - "4001:80"
  #   environment:
  #     - PORT=80
  #   restart: "no"
