version: "3"
services:
  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile.dev
    container_name: video-streaming
    ports:
      - "4000:80"
    volumes:
      - ./video-streaming:/src
    environment:
      - PORT=80
    restart: "no"

  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile.dev
    container_name: history
    ports:
      - "4001:80"
    environment:
      - PORT=80
    restart: "no"
