# Choose whatever you want, version >= 1.16
FROM golang:1.22 AS builder
ADD . /src
WORKDIR /src
ENV CGO_ENABLED=0
RUN go build -o main .

FROM scratch
WORKDIR /
COPY --from=builder /src/main /
ENV PORT=8080
ENTRYPOINT ["/main"]
